#!/usr/bin/python3
try:from pathlib import Path as P;R=P.resolve;E=P.exists; F = R(P(__file__));\
    L = lambda p: p / 'cfg.py'; from handyPyUtil import A; exec(A)
except: O=open(R(next(filter(E,map(L,F.parents))))); exec(O.read()); O.close()

import sys, os
import time
from threading import Thread, Event, Timer
from pathlib import Path
from more_itertools import first

from handyPyUtil.classes import DictToObj

from .. import client, server
from . import TestKitAS

from ..server import UsersTbl
from ..server.dbUsersTbl import DBUsersTbl
from .spawnUsers import spawnUsers

MYSQL_CNF = Path(sys.argv[0]).absolute().parent / 'mysql.cnf'

def execAdminCmd(gl, n, cmd, cb=None, relogin=False,
    expiresInSec = 0,  # for the `addAuthKey' command
):
    tk = gl.tk
    cliDicts = gl.cliDicts
    admLoggedIn = cliDicts['admin']['loggedIn'].wait(timeout=0.2)
    assert admLoggedIn

    admCli = cliDicts['admin']['cli']

    cliDict = cliDicts[n]
    u = cliDict['user']
    k = first(u.authKeys)

    sid = None
    if cmd in ('rmAuthUser',):
        cli = cliDict['cli']
        sid = cli.sock.get_sid()

    def onResponse(m):
        st = m.get('status', 63)
        assert st == 0, f"status={st}: {m.get('descr')}"

        if cb: cb()
        if relogin:
            cliDict['loggedIn'].wait(timeout=0.2)
            cli = cliDict['cli']
            cli.login()

    m = {
        'type': 'admin',
        'command': cmd,
        'username': n,
        'authKey': k,
        'sid': sid,
        'callback': onResponse,
    }
    if cmd == 'addAuthKey':
        m['expiresInSec'] = expiresInSec

    admCli.pushMessage(m)
    admCli.sendMessages()


def startServer(gl):
    case = gl.case
    tk = gl.tk
    cliDicts = gl.cliDicts

    UsersTblCls = case.UsersTblCls

    usersTbl_kwarg = {
        'idleSessionDurSec': 2,
    }
    srv_kwarg = {
        'UsersTblCls': UsersTblCls,
        'usersTbl_kwarg': usersTbl_kwarg,
        'adminAuthKey': first(cliDicts['admin']['user'].authKeys),
    }

    if UsersTblCls is UsersTbl:
        srv_kwarg.update({
            'authUsersInMem': True,
        })
    elif issubclass(UsersTblCls, DBUsersTbl):
        usersTbl_kwarg.update({'secBtwExpiryCleanups': 1})
        srv_kwarg.update({
            'read_default_file': MYSQL_CNF,
        })
    else: raise Exception(f'unsupported UsersTblCls={type(UsersTblCls)}')

    tk.startServer(**srv_kwarg)
    time.sleep(case.maxInitSec)

def registerUsers(gl):
    cliDicts = gl.cliDicts
    cliDicts['admin']['loggedIn'].wait(0.2)

    registered = []
    # add user0's key
    for n in ('user0',):
        r = Event()
        def cb(r=r): r.set()
        execAdminCmd(gl, n, "addAuthKey", expiresInSec=1, cb=cb)
        registered.append(r)

    for r in registered:
        rst = r.wait(0.2)
        if not rst:
            tk.logger.error(f'user was not registered!')

def synchClock(gl):
    tk = gl.tk
    cliDicts = gl.cliDicts
    for n in ('admin', 'user0'):
        cliDict = cliDicts[n]
        assert cliDict['loggedIn'].wait(0.5), f'user {n} has not logged in'
    tk.logger.debug(f'clock synchronised at {time.time()}')

def waitUntilT(dsec, sec0):
    time.sleep(max(0, dsec - (time.time() - sec0)))

def echoWorks(cli):
    "Return True iff the echo client command receives a response"

    rspReceived = Event()
    def cb(m):  rspReceived.set()
    cli.pushMessage({
        'type': 'echo',
        'callback': cb,
    }, send=True)

    return rspReceived.wait(0.2)

def loginWorks(gl, cli):
    tk = gl.tk
    Timer(0.1, cli.login).start()
    m = next(cli.listenToMessages(timeout=0.2))
    tk.logger.debug(f'loginWorks() (user {cli.user}) received message: {m}')
    return bool(m and m['type'] == 'auth' and m['status'] == 0)

def adminOnAuth(cli, gl, authst):
    "Admin actions after authentication go here"

    assert cli.user == 'admin'
    assert authst.status == 0

    tk = gl.tk
    cliDicts = gl.cliDicts
    synchClock(gl)

    t0 = time.time()

    waitUntilT(2, t0)

    # t = 2 sec

    # add user1's key
    execAdminCmd(gl, 'user1', "addAuthKey", expiresInSec=60)

    waitUntilT(4, t0)

    # t = 4 sec

    allCliOk = True
    for n, cliDict in sorted(cliDicts.items(), key=lambda it: it[0]):
        if n == 'admin': continue
        if not cliDict['success'].isSet():
            allCliOk = False
            tk.logger.error(f'user {n} did not pass the test')

    if allCliOk:
        gl.testCaseSuccess.set()

def userOnAuth(cli, gl, authst):
    "Client actions after the FIRST authentication go here"

    usedFlag = 'alreadyUsed_' + cli.user
    if hasattr(userOnAuth, usedFlag): return
    else:
        setattr(userOnAuth, usedFlag, True)

    tk = gl.tk
    tk.logger.debug(f'entering userOnAuth()')

    synchClock(gl)

    n = cli.user
    cliDict = gl.cliDicts[n]
    u = cliDict['user']
    cli = cliDict['cli']

    t0 = time.time()
    if u.index == 0:
        # 1. make sure user0 is connected at t = 0
        assert authst.status == 0
        assert echoWorks(cli)

        waitUntilT(3, t0)

        # t = 3 sec

        # 2. make sure user0 can't connect at t = 3 (admin cleaned key at t=2)
        assert not loginWorks(gl, cli)
    elif u.index == 1:
        # 1. make sure user1 can't connect at t = 0
        assert authst.status != 0
        assert not loginWorks(gl, cli)
        tk.logger.debug(f'user1 cannot connect at t~=0 (as expected)')

        waitUntilT(3, t0)

        # t = 3 sec

        # 2. make sure user1 can connect at t = 3 (admin added key at t=2)
        assert loginWorks(gl, cli)
        tk.logger.debug(f'user1 CAN connect at t~=3 (as expected)')
    else: raise Exception(f'cannot process user {u.name}')

    tk.logger.debug(f'setting the success event for user {u.name}')
    cliDict['success'].set()

def startClients(gl, ns):
    class SMAClass_cli(client.ServerMessageArray):
        def on_auth(self, m):
            authst = super().on_auth(m)
            cli = self.cli
            cliDict = gl.cliDicts[cli.user]
            cliDict['cli'] = cli

            cli.logger.info(f'received an auth message from the server; user={cli.user}; status={authst}')

            if authst.status == 0:
                cliDict['loggedIn'].set()

            if cli.user == 'admin':
                adminOnAuth(cli, gl, authst)
            else:
                userOnAuth(cli, gl, authst)

        def on_admin(self, m): pass

    cliDicts = gl.cliDicts
    tk = gl.tk

    for n in ns:
        cliDict = cliDicts[n]
        u = cliDict['user']
        cli, thCli = tk.startClient(SMAClass=SMAClass_cli, user=u)
        cliDict.update({'cli': cli, 'thCli': thCli})

def initCliSrv(gl):
    cliDicts = gl.cliDicts

    startServer(gl)
    startClients(gl, ('admin',))
    registerUsers(gl)
    startClients(gl, tuple(n for n in cliDicts if n != 'admin'))

def doTest(case):
    with TestKitAS() as tk:
        cliDicts = spawnUsers(case.NUsers, genAuthKeys=True)
        for cliDict in cliDicts.values(): cliDict['success'] = Event()

        gl = DictToObj({
            'case': case,
            'cliDicts': cliDicts,
            'tk': tk,
            'testCaseSuccess': Event(),
        })

        initCliSrv(gl)
        gl.testCaseSuccess.wait(4 + gl.case.NUsers * 0.5)
        assert gl.testCaseSuccess.isSet()

NUsersAllCases = 2

cases = [
    DictToObj({
        'NUsers': NUsersAllCases,
        'UsersTblCls': DBUsersTbl,
        'maxInitSec': 0.3
    }),
]

for case in cases:
    doTest(case)
