#!/usr/bin/python3
try:from pathlib import Path as P;R=P.resolve;E=P.exists; F = R(P(__file__));\
    L = lambda p: p / 'cfg.py'; from handyPyUtil import A; exec(A)
except: O=open(R(next(filter(E,map(L,F.parents))))); exec(O.read()); O.close()

import time
from threading import Thread, Event

from arraySocket import client, server, ASUser
from . import TestKitAS

def onAuth(cli, case, success):
    def callback(m):
        assert isinstance(m, dict)
        success.set()

    cli.pushMessage({
        'type': 'test',
        'callback': callback,
    })
    cli.sendMessages()

def doTest(case):
    u = ASUser(name='john', authKeys=('secret',))

    with TestKitAS() as tk:
        success = Event()

        SMAClass_srv = server.ServerMessageArray.cloneClass(
            add_MSG_TYPES = ('test',),
        )

        class CMAClass_srv(server.ClientMessageArray.cloneClass(
            add_MSG_TYPES = ('test',),
        )):
            def on_test(self, m):
                self.pushMessage({
                    'type': 'test',
                }, cbFromCliMsg=m)

        class SMAClass_cli(client.ServerMessageArray):
            def on_auth(self, m):
                s = super().on_auth(m)
                assert s.status == 0

                onAuth(self.cli, case, success)
            def on_test(self, m): pass

        srvProc = tk.startServer(
            SMAClass=SMAClass_srv,
            CMAClass=CMAClass_srv,
            staticUsers=[u],
            authUsersInMem = True,
        )
        time.sleep(0.1)

        cli, thCli = tk.startClient(SMAClass=SMAClass_cli, user=u)

        success.wait(0.1)
        assert success.isSet()

cases = [
    {
    },
]

for case in cases: doTest(case)
