#!/usr/bin/python3
from pathlib import Path as P; E=P.exists;R=P.resolve; l=R(P(__file__)).parents
with open(R(next(filter(E,(p/'cfg.py' for p in l))))) as _:exec(_.read())

inclPath()

import time
from threading import Thread, Event

import client
from TestKitAS import TestKitAS, DFLT_TEST_PORT

with TestKitAS() as tk:
    srvProc = tk.startServer()

    authSuccess = Event()

    class SMAClass(client.ServerMessageArray):
        def on_auth(self, m):
            super().on_auth(m)
            print('auth success')
            authSuccess.set()

    class Cli(client.Client):
        def onConnect(self):
            super().onConnect()

    
    cli = Cli(f"http://127.0.0.1:{DFLT_TEST_PORT}", SMAClass=SMAClass)

    def trgCli():
        cli.run()
    time.sleep(1)
    thCli = Thread(target=trgCli)
    thCli.start()

    authSuccess.wait(2)
    cli.stop()
    srvProc.join(1)
    assert authSuccess.isSet()
