#!/usr/bin/python3
from pathlib import Path as P; E=P.exists;R=P.resolve; l=R(P(__file__)).parents
with open(R(next(filter(E,(p/'cfg.py' for p in l))))) as _:exec(_.read())

inclPath()

import time

from client import Client
from TestKitAS import TestKitAS, DFLT_TEST_PORT

with TestKitAS() as tk:
    tk.startServer()

    time.sleep(1)
    
    cli = Client(f"http://127.0.0.1:{DFLT_TEST_PORT}")
    def trgCli():
        cli.run()

    from threading import Thread
    thCli = Thread(target=trgCli)
    thCli.start()

    time.sleep(2)
    cli.stop()
