#!/usr/bin/python3
from pathlib import Path as P; E=P.exists;R=P.resolve; l=R(P(__file__)).parents
with open(R(next(filter(E,(p/'cfg.py' for p in l))))) as _:exec(_.read())

inclPath()

import time
from threading import Thread, Event

import client
from TestKitAS import TestKitAS, DFLT_TEST_PORT

with TestKitAS() as tk:
    srvProc = tk.startServer()

    authExchange = Event()

    class SMAClass(client.ServerMessageArray):
        def on_auth(self, m):
            authExchange.set()
            super().on_auth(m)

    class Cli(client.Client):
        def onConnect(self):
            super().onConnect()

    time.sleep(0.1)
    cli = Cli(f"http://127.0.0.1:{DFLT_TEST_PORT}", SMAClass=SMAClass)

    def trgCli():
        cli.run()
    thCli = Thread(target=trgCli)
    thCli.start()

    authExchange.wait(0.1)
    cli.stop()

    assert authExchange.isSet()
